import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StatementsProvider } from "@/components/data-context";
import { getCsvData } from "@/lib/read-csv";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // fetch CSV data 
  const statements = await getCsvData();
  // pass raw data to the StatementsProvider which uses the createStatements function to transform it into the Statement type 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StatementsProvider data={statements}>{children}</StatementsProvider>
      </body>
    </html>
  );
}
